#!/bin/sh

set -e

mono_version="$1"

if [ "$mono_version" == "" ]; then
  echo "usage: $0 VERSION"
  exit 1
fi

if [ "$AWS_ACCOUNT_ID" == "" ]; then
  echo "must set AWS_ACCOUNT_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t mono_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
pushd $tempdir

# download and extract mono
cp /tmp/mono-${mono_version}.tar.gz .
cp -r /tmp/mono-${mono_version} .
curl -O http://download.mono-project.com/sources/mono/mono-${mono_version}.tar.gz
tar xzvf mono-${mono_version}.tar.gz

# go into mono dir
pushd mono-${mono_version}

# build and package mono for heroku
vulcan build -v -p /app/mono -c "./configure --prefix=/app/mono --sysconfdir=/app/mono --disable-nls && make && make install"

# upload monojs to s3
$basedir/aws/s3 put $S3_BUCKET \
  mono-${mono_version}.tgz $tempdir/mono-${mono_version}.tgz

