#!/bin/sh

set -e

xsp_version="$1"

if [ "$xsp_version" == "" ]; then
  echo "usage: $0 VERSION"
  exit 1
fi

if [ "$AWS_ACCOUNT_ID" == "" ]; then
  echo "must set AWS_ACCOUNT_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

if [ "$MONO_VERSION" == "" ]; then
  echo "must set MONO_VERSION"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t xsp_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
pushd $tempdir

# download and extract XSP
cp /tmp/xsp-${xsp_version}.tar.gz .
cp -r /tmp/xsp-${xsp_version} .
curl -O http://ftp.novell.com/pub/mono/sources/xsp/xsp-${xsp_version}.tar.bz2
tar xjvf xsp-${xsp_version}.tar.bz2

# go into XSP dir
pushd xsp-${xsp_version}

MONO_PACKAGE="https://s3.amazonaws.com/heroku-buildpack-mono/mono-${MONO_VERSION}.tgz"

# build and package XSP for heroku
vulcan build -v -p /app/xsp -c "PATH=\"/app/mono/bin:$PATH\" PKG_CONFIG_PATH=\"/app/mono/lib/pkgconfig/:$PKG_CONFIG_PATH\" curl --silent --max-time 60 --location $MONO_PACKAGE | tar xz - -C /app && ./configure --prefix=/app/xsp --sysconfdir=/app/xsp && make && make install"

# upload XSP to s3
$basedir/aws/s3 put $S3_BUCKET \
  xsp-${xsp_version}.tgz $tempdir/xsp-${xsp_version}.tgz

